require "metaheuristic_algorithms/function_wrappers/abstract_wrapper"
require "metaheuristic_algorithms/function_wrappers/rosenbrook_function_wrapper"
require "metaheuristic_algorithms/function_wrappers/nonsmooth_multipeak_function_wrapper"
require "metaheuristic_algorithms/function_wrappers/easom_function_wrapper"
require "metaheuristic_algorithms/function_wrappers/michaelwicz_function_wrapper"

module MetaheuristicAlgorithms

  module FunctionWrappers
    
  end

end